# Generated by Django 5.1 on 2024-09-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secoes', '0002_alter_secao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secao',
            old_name='id',
            new_name='secao_id',
        ),
    ]
