# Generated by Django 5.1 on 2024-09-01 21:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='instrucoes_imagens/')),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoes.secao')),
            ],
        ),
    ]
