# Generated by Django 5.1 on 2024-09-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrucoes', '0002_alter_instrucao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrucao',
            old_name='id',
            new_name='instrucao_id',
        ),
    ]
