# Generated by Django 5.1 on 2024-09-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrucoes', '0003_rename_id_instrucao_instrucao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrucao',
            old_name='instrucao_id',
            new_name='id',
        ),
    ]
